/**
 * POST /api/node/activate
 *
 * Real node activation. Given an existing nodeId (from /api/genesis), creates
 * a signed activation receipt binding the resource-sharing commitment.
 *
 * Expects: { nodeId: string, resourceSettings: {...} }
 * Returns: { receiptId, receiptHash, signature, activatedAt }
 */

import { NextRequest, NextResponse } from "next/server";
import { generateKeyPairSync, sign, createHash } from "node:crypto";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function sha256(input: string | Buffer): string {
  return createHash("sha256").update(input).digest("hex");
}

function hex(buf: Buffer | Uint8Array): string {
  return Buffer.from(buf).toString("hex");
}

interface ResourceSettings {
  cpuShare: number;
  gpuShare: number;
  storageShare: number;
  alwaysAvailable: boolean;
  availableHours: [number, number];
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  let body: { nodeId?: string; resourceSettings?: ResourceSettings } = {};
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const nodeId = (body.nodeId ?? "").trim();
  const rs = body.resourceSettings;

  if (!/^[0-9a-f]{64}$/.test(nodeId)) {
    return NextResponse.json({ error: "invalid nodeId" }, { status: 400 });
  }
  if (
    !rs ||
    typeof rs.cpuShare !== "number" ||
    typeof rs.gpuShare !== "number" ||
    typeof rs.storageShare !== "number" ||
    typeof rs.alwaysAvailable !== "boolean"
  ) {
    return NextResponse.json({ error: "resourceSettings required" }, { status: 400 });
  }
  if (rs.cpuShare < 0 || rs.cpuShare > 80 || rs.gpuShare < 0 || rs.gpuShare > 80 || rs.storageShare < 0 || rs.storageShare > 80) {
    return NextResponse.json({ error: "share out of range" }, { status: 400 });
  }
  if (
    rs.availableHours != null &&
    (!Array.isArray(rs.availableHours) || rs.availableHours.length !== 2 ||
      typeof rs.availableHours[0] !== "number" || typeof rs.availableHours[1] !== "number" ||
      rs.availableHours[0] < 0 || rs.availableHours[1] > 24 || rs.availableHours[0] > rs.availableHours[1])
  ) {
    return NextResponse.json({ error: "availableHours must be [start, end] in 0-24" }, { status: 400 });
  }

  const activatedAt = new Date().toISOString();
  const receipt = {
    type: "node.activation.v1",
    nodeId,
    resourceSettings: {
      cpuShare: rs.cpuShare,
      gpuShare: rs.gpuShare,
      storageShare: rs.storageShare,
      alwaysAvailable: rs.alwaysAvailable,
      availableHours: rs.availableHours,
    },
    activatedAt,
    constitutionVersion: "5.0.0-GENESIS",
  };
  const receiptJson = JSON.stringify(receipt);
  const receiptHash = sha256(receiptJson);

  // Sign receipt with an ephemeral key. Note: this proves the receipt was
  // generated by this endpoint at this time; durable node-key-signed receipts
  // require the Python sovereign backend (forthcoming wire-up).
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  const pubDer = publicKey.export({ type: "spki", format: "der" });
  const pubRaw = pubDer.subarray(pubDer.length - 32);
  const signature = sign(null, Buffer.from(receiptJson), privateKey);

  return NextResponse.json(
    {
      receiptId: receiptHash.slice(0, 32),
      receiptHash,
      signerPublicKey: hex(pubRaw),
      signature: hex(signature),
      activatedAt,
      receipt,
      signerMode: "ephemeral_edge",
      note: "Edge-signed activation receipt. Node-key-signed receipts require sovereign backend integration.",
    },
    { status: 200, headers: { "Cache-Control": "no-store" } }
  );
}
