/*
 * This module intentionally stays valid JavaScript despite its .ts suffix.
 * The capture CLI loads the same inventory as source text on Node 20+, which
 * keeps the inventory single-sourced without adding a runtime transpiler.
 */

export const PUBLIC_PAGE_SURFACES = Object.freeze([
  Object.freeze({
    id: 'page:/',
    kind: 'page',
    route: '/',
    sourcePath: 'app/page.tsx',
    access: 'public',
    disposition: 'reviewed',
    capture: true,
    rationale: 'The dated public truth boundary is the only reviewed page.',
  }),
  Object.freeze({
    id: 'page:/atlas',
    kind: 'page',
    route: '/atlas',
    sourcePath: 'app/atlas/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Legacy architecture claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/book',
    kind: 'page',
    route: '/book',
    sourcePath: 'app/book/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Legacy narrative claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/dema',
    kind: 'page',
    route: '/dema',
    sourcePath: 'app/dema/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Legacy Dema capability claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/docs',
    kind: 'page',
    route: '/docs',
    sourcePath: 'app/docs/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Legacy documentation claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/genesis',
    kind: 'page',
    route: '/genesis',
    sourcePath: 'app/genesis/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Genesis and activation claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/info',
    kind: 'page',
    route: '/info',
    sourcePath: 'app/info/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Legacy product claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/invites/[token]',
    kind: 'page',
    route: '/invites/[token]',
    sourcePath: 'app/invites/[token]/page.tsx',
    access: 'secret-parameterized',
    disposition: 'exclude-secret',
    capture: false,
    rationale: 'An invite token is a credential and must never enter public capture.',
  }),
  Object.freeze({
    id: 'page:/lab',
    kind: 'page',
    route: '/lab',
    sourcePath: 'app/lab/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Unbound measured and verified labels remain contained.',
  }),
  Object.freeze({
    id: 'page:/login',
    kind: 'page',
    route: '/login',
    sourcePath: 'app/login/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'The legacy login surface is not part of the reviewed public boundary.',
  }),
  Object.freeze({
    id: 'page:/manifest',
    kind: 'page',
    route: '/manifest',
    sourcePath: 'app/manifest/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Manifest and roadmap claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/research',
    kind: 'page',
    route: '/research',
    sourcePath: 'app/research/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Research claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/settings/team',
    kind: 'page',
    route: '/settings/team',
    sourcePath: 'app/settings/team/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'The unaudited team shell remains contained at the public edge.',
  }),
  Object.freeze({
    id: 'page:/showcase',
    kind: 'page',
    route: '/showcase',
    sourcePath: 'app/showcase/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Showcase claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/showcase/maestro',
    kind: 'page',
    route: '/showcase/maestro',
    sourcePath: 'app/showcase/maestro/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Maestro capability claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/showcase/pipeline',
    kind: 'page',
    route: '/showcase/pipeline',
    sourcePath: 'app/showcase/pipeline/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Pipeline capability claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/terminal',
    kind: 'page',
    route: '/terminal',
    sourcePath: 'app/terminal/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Terminal and runtime claims remain contained pending claim binding.',
  }),
  Object.freeze({
    id: 'page:/wallet',
    kind: 'page',
    route: '/wallet',
    sourcePath: 'app/wallet/page.tsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Token and economic claims remain contained pending claim binding.',
  }),
]);

export const PUBLIC_METADATA_SURFACES = Object.freeze([
  Object.freeze({
    id: 'metadata:/sitemap.xml',
    kind: 'metadata',
    route: '/sitemap.xml',
    sourcePath: 'app/sitemap.ts',
    access: 'public',
    disposition: 'reviewed',
    capture: true,
    rationale:
      'The middleware matcher intentionally bypasses this dated root-only sitemap.',
  }),
]);

export const PUBLIC_STATIC_TEXT_SURFACES = Object.freeze([
  Object.freeze({
    id: 'static:/architecture-atlas.html',
    kind: 'static-text',
    route: '/architecture-atlas.html',
    sourcePath: 'public/architecture-atlas.html',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Legacy architecture assertions remain contained.',
  }),
  Object.freeze({
    id: 'static:/data/metrics.json',
    kind: 'static-text',
    route: '/data/metrics.json',
    sourcePath: 'public/data/metrics.json',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Unbound metric values remain contained.',
  }),
  Object.freeze({
    id: 'static:/films/BIZRA%20Federation%20Atlas.dc.html',
    kind: 'static-text',
    route: '/films/BIZRA%20Federation%20Atlas.dc.html',
    sourcePath: 'public/films/BIZRA Federation Atlas.dc.html',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Federation film claims remain contained.',
  }),
  Object.freeze({
    id: 'static:/films/BIZRA%20Mission%20Thesis.dc.html',
    kind: 'static-text',
    route: '/films/BIZRA%20Mission%20Thesis.dc.html',
    sourcePath: 'public/films/BIZRA Mission Thesis.dc.html',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Mission film claims remain contained.',
  }),
  Object.freeze({
    id: 'static:/films/BIZRA%20The%20Third%20Fact.dc.html',
    kind: 'static-text',
    route: '/films/BIZRA%20The%20Third%20Fact.dc.html',
    sourcePath: 'public/films/BIZRA The Third Fact.dc.html',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Third Fact film claims remain contained.',
  }),
  Object.freeze({
    id: 'static:/films/animations-v2.jsx',
    kind: 'static-text',
    route: '/films/animations-v2.jsx',
    sourcePath: 'public/films/animations-v2.jsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Public film source can carry visible claims and remains contained.',
  }),
  Object.freeze({
    id: 'static:/films/bizra-federation-atlas.jsx',
    kind: 'static-text',
    route: '/films/bizra-federation-atlas.jsx',
    sourcePath: 'public/films/bizra-federation-atlas.jsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Federation film source can carry visible claims and remains contained.',
  }),
  Object.freeze({
    id: 'static:/films/bizra-mission-thesis.jsx',
    kind: 'static-text',
    route: '/films/bizra-mission-thesis.jsx',
    sourcePath: 'public/films/bizra-mission-thesis.jsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Mission film source can carry visible claims and remains contained.',
  }),
  Object.freeze({
    id: 'static:/films/bizra-third-fact.jsx',
    kind: 'static-text',
    route: '/films/bizra-third-fact.jsx',
    sourcePath: 'public/films/bizra-third-fact.jsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Third Fact film source can carry visible claims and remains contained.',
  }),
  Object.freeze({
    id: 'static:/films/index.html',
    kind: 'static-text',
    route: '/films/index.html',
    sourcePath: 'public/films/index.html',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'The legacy film index remains contained.',
  }),
  Object.freeze({
    id: 'static:/films/support.js',
    kind: 'static-text',
    route: '/films/support.js',
    sourcePath: 'public/films/support.js',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Public film support source remains contained.',
  }),
  Object.freeze({
    id: 'static:/films/tweaks-panel.jsx',
    kind: 'static-text',
    route: '/films/tweaks-panel.jsx',
    sourcePath: 'public/films/tweaks-panel.jsx',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Public film control source remains contained.',
  }),
  Object.freeze({
    id: 'static:/install/index.html',
    kind: 'static-text',
    route: '/install/index.html',
    sourcePath: 'public/install/index.html',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Installer availability claims remain contained.',
  }),
  Object.freeze({
    id: 'static:/robots.txt',
    kind: 'static-text',
    route: '/robots.txt',
    sourcePath: 'public/robots.txt',
    access: 'public',
    disposition: 'reviewed',
    capture: true,
    rationale:
      'The middleware matcher intentionally bypasses this public crawl policy.',
  }),
  Object.freeze({
    id: 'static:/sovereign-emergence.html',
    kind: 'static-text',
    route: '/sovereign-emergence.html',
    sourcePath: 'public/sovereign-emergence.html',
    access: 'public',
    disposition: 'contain',
    capture: true,
    rationale: 'Legacy sovereign-system claims remain contained.',
  }),
]);

export const PUBLIC_GET_API_SURFACES = Object.freeze([
  Object.freeze({
    id: 'api:/api/auth/me',
    kind: 'api',
    method: 'GET',
    route: '/api/auth/me',
    sourcePath: 'app/api/auth/me/route.ts',
    access: 'authenticated',
    disposition: 'exclude-authenticated',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/beta/status',
    kind: 'api',
    method: 'GET',
    route: '/api/beta/status',
    sourcePath: 'app/api/beta/status/route.ts',
    access: 'public',
    disposition: 'audit',
    capture: true,
    rationale: 'Middleware explicitly exposes the no-secret beta state.',
  }),
  Object.freeze({
    id: 'api:/api/chain/[hash]',
    kind: 'api',
    method: 'GET',
    route: '/api/chain/[hash]',
    sourcePath: 'app/api/chain/[hash]/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-authenticated',
    capture: false,
    rationale: 'Middleware requires authentication and a receipt identifier.',
  }),
  Object.freeze({
    id: 'api:/api/chain',
    kind: 'api',
    method: 'GET',
    route: '/api/chain',
    sourcePath: 'app/api/chain/route.ts',
    access: 'authenticated',
    disposition: 'exclude-authenticated',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/csrf-token',
    kind: 'api',
    method: 'GET',
    route: '/api/csrf-token',
    sourcePath: 'app/api/csrf-token/route.ts',
    access: 'public-sensitive',
    disposition: 'exclude-secret',
    capture: false,
    rationale: 'The endpoint mints a CSRF credential and cookies.',
  }),
  Object.freeze({
    id: 'api:/api/ethics',
    kind: 'api',
    method: 'GET',
    route: '/api/ethics',
    sourcePath: 'app/api/ethics/route.ts',
    access: 'authenticated',
    disposition: 'exclude-authenticated',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/gates/[missionId]',
    kind: 'api',
    method: 'GET',
    route: '/api/gates/[missionId]',
    sourcePath: 'app/api/gates/[missionId]/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-authenticated',
    capture: false,
    rationale: 'Middleware requires authentication and a mission identifier.',
  }),
  Object.freeze({
    id: 'api:/api/health',
    kind: 'api',
    method: 'GET',
    route: '/api/health',
    sourcePath: 'app/api/health/route.ts',
    access: 'public',
    disposition: 'audit',
    capture: true,
    rationale: 'Middleware explicitly exposes only the non-verbose health response.',
  }),
  Object.freeze({
    id: 'api:/api/invites/[token]',
    kind: 'api',
    method: 'GET',
    route: '/api/invites/[token]',
    sourcePath: 'app/api/invites/[token]/route.ts',
    access: 'secret-parameterized',
    disposition: 'exclude-secret',
    capture: false,
    rationale: 'The public lookup requires an invite credential.',
  }),
  Object.freeze({
    id: 'api:/api/knowledge-graph',
    kind: 'api',
    method: 'GET',
    route: '/api/knowledge-graph',
    sourcePath: 'app/api/knowledge-graph/route.ts',
    access: 'authenticated',
    disposition: 'exclude-private-data',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/manifest/today',
    kind: 'api',
    method: 'GET',
    route: '/api/manifest/today',
    sourcePath: 'app/api/manifest/today/route.ts',
    access: 'authenticated',
    disposition: 'exclude-authenticated',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/metrics',
    kind: 'api',
    method: 'GET',
    route: '/api/metrics',
    sourcePath: 'app/api/metrics/route.ts',
    access: 'authenticated',
    disposition: 'exclude-private-data',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/missions/[id]',
    kind: 'api',
    method: 'GET',
    route: '/api/missions/[id]',
    sourcePath: 'app/api/missions/[id]/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-authenticated',
    capture: false,
    rationale: 'Middleware requires authentication and a mission identifier.',
  }),
  Object.freeze({
    id: 'api:/api/scaffold/evidence',
    kind: 'api',
    method: 'GET',
    route: '/api/scaffold/evidence',
    sourcePath: 'app/api/scaffold/evidence/route.ts',
    access: 'authenticated',
    disposition: 'exclude-private-data',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/scaffold/genesis-seal',
    kind: 'api',
    method: 'GET',
    route: '/api/scaffold/genesis-seal',
    sourcePath: 'app/api/scaffold/genesis-seal/route.ts',
    access: 'authenticated',
    disposition: 'exclude-private-data',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/scaffold/health',
    kind: 'api',
    method: 'GET',
    route: '/api/scaffold/health',
    sourcePath: 'app/api/scaffold/health/route.ts',
    access: 'authenticated',
    disposition: 'exclude-private-data',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  Object.freeze({
    id: 'api:/api/scaffold/metrics',
    kind: 'api',
    method: 'GET',
    route: '/api/scaffold/metrics',
    sourcePath: 'app/api/scaffold/metrics/route.ts',
    access: 'authenticated',
    disposition: 'exclude-private-data',
    capture: true,
    retainPublicText: false,
    rationale:
      'Probe the fixed route without credentials, retaining status and body hash only.',
  }),
  ...[
    'health',
    'health/live',
    'health/ready',
    'health/deep',
    'status',
    'metrics',
    'cognitive/status',
    'verify/genesis',
    'verify/envelope',
    'verify/receipt',
    'verify/audit-log',
    'verify/ledger',
    'verify/poi',
    'verify/signature',
    'verify/genesis/header',
    'token/supply',
    'token/verify',
  ].map((path) =>
    Object.freeze({
      id: `api:/api/v1/${path}`,
      kind: 'api',
      method: 'GET',
      route: `/api/v1/${path}`,
      sourcePath: 'app/api/v1/[...path]/route.ts',
      access: 'authenticated',
      disposition: 'exclude-authenticated',
      capture: true,
      retainPublicText: false,
      rationale:
        'Probe the fixed allowlisted path without credentials, retaining status and body hash only.',
    })
  ),
  Object.freeze({
    id: 'api:/api/workspaces/[workspaceId]/invites',
    kind: 'api',
    method: 'GET',
    route: '/api/workspaces/[workspaceId]/invites',
    sourcePath: 'app/api/workspaces/[workspaceId]/invites/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-private-data',
    capture: false,
    rationale: 'Workspace invites contain personal and credential-adjacent data.',
  }),
  Object.freeze({
    id: 'api:/api/workspaces/[workspaceId]/members',
    kind: 'api',
    method: 'GET',
    route: '/api/workspaces/[workspaceId]/members',
    sourcePath: 'app/api/workspaces/[workspaceId]/members/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-private-data',
    capture: false,
    rationale: 'Workspace membership contains personal identity and role data.',
  }),
]);

export const NON_GET_API_METHOD_SURFACES = Object.freeze([
  Object.freeze({
    id: 'api:POST:/api/auth/login',
    kind: 'api',
    method: 'POST',
    route: '/api/auth/login',
    sourcePath: 'app/api/auth/login/route.ts',
    access: 'public-integrity-hold',
    disposition: 'hold-auth-integrity',
    capture: false,
    rationale:
      'Login returns AUTH_INTEGRITY_HOLD until a production identity provider is trusted.',
  }),
  Object.freeze({
    id: 'api:PUT:/api/auth/login',
    kind: 'api',
    method: 'PUT',
    route: '/api/auth/login',
    sourcePath: 'app/api/auth/login/route.ts',
    access: 'public-integrity-hold',
    disposition: 'hold-auth-integrity',
    capture: false,
    rationale:
      'Refresh returns AUTH_INTEGRITY_HOLD until a production identity provider is trusted.',
  }),
  Object.freeze({
    id: 'api:DELETE:/api/auth/login',
    kind: 'api',
    method: 'DELETE',
    route: '/api/auth/login',
    sourcePath: 'app/api/auth/login/route.ts',
    access: 'authenticated',
    disposition: 'allow-authenticated-logout',
    capture: false,
    rationale:
      'Only an existing authenticated session may execute the bounded logout path.',
  }),
  Object.freeze({
    id: 'api:POST:/api/beta/verify-invite',
    kind: 'api',
    method: 'POST',
    route: '/api/beta/verify-invite',
    sourcePath: 'app/api/beta/verify-invite/route.ts',
    access: 'public-beta-secret-input',
    disposition: 'beta-before-public',
    capture: false,
    rationale:
      'The public beta admission check consumes an invitation secret and may mint an admission cookie.',
  }),
  Object.freeze({
    id: 'api:POST:/api/csrf-token',
    kind: 'api',
    method: 'POST',
    route: '/api/csrf-token',
    sourcePath: 'app/api/csrf-token/route.ts',
    access: 'public-secret-input',
    disposition: 'exclude-secret',
    capture: false,
    rationale: 'CSRF verification consumes security tokens and cookies.',
  }),
  Object.freeze({
    id: 'api:POST:/api/ethics',
    kind: 'api',
    method: 'POST',
    route: '/api/ethics',
    sourcePath: 'app/api/ethics/route.ts',
    access: 'authenticated',
    disposition: 'exclude-authenticated',
    capture: false,
    rationale:
      'Middleware requires authentication and CSRF validation before metrics mutation.',
  }),
  Object.freeze({
    id: 'api:POST:/api/genesis',
    kind: 'api',
    method: 'POST',
    route: '/api/genesis',
    sourcePath: 'app/api/genesis/route.ts',
    access: 'beta-gated-authenticated-mutation',
    disposition: 'beta-before-public',
    capture: false,
    rationale:
      'Invite-only admission is evaluated before the public route pass; middleware then requires authentication and the handler checks admission again.',
  }),
  Object.freeze({
    id: 'api:HEAD:/api/health',
    kind: 'api',
    method: 'HEAD',
    route: '/api/health',
    sourcePath: 'app/api/health/route.ts',
    access: 'public',
    disposition: 'audit',
    capture: false,
    rationale:
      'The public health probe has no body, but non-GET capture is prohibited.',
  }),
  Object.freeze({
    id: 'api:POST:/api/invites/[token]/accept',
    kind: 'api',
    method: 'POST',
    route: '/api/invites/[token]/accept',
    sourcePath: 'app/api/invites/[token]/accept/route.ts',
    access: 'authenticated-secret-parameterized',
    disposition: 'exclude-secret',
    capture: false,
    rationale:
      'Invite acceptance requires authentication, CSRF validation, and a secret token.',
  }),
  Object.freeze({
    id: 'api:POST:/api/missions/[id]/replay',
    kind: 'api',
    method: 'POST',
    route: '/api/missions/[id]/replay',
    sourcePath: 'app/api/missions/[id]/replay/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-authenticated',
    capture: false,
    rationale:
      'Mission replay requires authentication, CSRF validation, and a mission identifier.',
  }),
  Object.freeze({
    id: 'api:POST:/api/missions',
    kind: 'api',
    method: 'POST',
    route: '/api/missions',
    sourcePath: 'app/api/missions/route.ts',
    access: 'authenticated',
    disposition: 'exclude-authenticated',
    capture: false,
    rationale:
      'Mission creation requires authentication and CSRF validation.',
  }),
  Object.freeze({
    id: 'api:POST:/api/node/activate',
    kind: 'api',
    method: 'POST',
    route: '/api/node/activate',
    sourcePath: 'app/api/node/activate/route.ts',
    access: 'beta-gated-authenticated-mutation',
    disposition: 'beta-before-public',
    capture: false,
    rationale:
      'Invite-only admission is evaluated before the public route pass; middleware then requires authentication and the handler checks admission again.',
  }),
  ...['POST', 'PUT', 'PATCH', 'DELETE'].map((method) =>
    Object.freeze({
      id: `api:${method}:/api/v1/[...path]`,
      kind: 'api',
      method,
      route: '/api/v1/[...path]',
      sourcePath: 'app/api/v1/[...path]/route.ts',
      access: 'authenticated-parameterized',
      disposition: 'exclude-authenticated',
      capture: false,
      rationale:
        'Site middleware requires authentication and CSRF validation before proxy mutations.',
    })
  ),
  Object.freeze({
    id: 'api:POST:/api/workspaces/[workspaceId]/invites/[inviteId]/resend',
    kind: 'api',
    method: 'POST',
    route: '/api/workspaces/[workspaceId]/invites/[inviteId]/resend',
    sourcePath:
      'app/api/workspaces/[workspaceId]/invites/[inviteId]/resend/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-private-data',
    capture: false,
    rationale:
      'Resend requires authenticated workspace authority, CSRF validation, and private identifiers.',
  }),
  Object.freeze({
    id: 'api:POST:/api/workspaces/[workspaceId]/invites/[inviteId]/revoke',
    kind: 'api',
    method: 'POST',
    route: '/api/workspaces/[workspaceId]/invites/[inviteId]/revoke',
    sourcePath:
      'app/api/workspaces/[workspaceId]/invites/[inviteId]/revoke/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-private-data',
    capture: false,
    rationale:
      'Revocation requires authenticated workspace authority, CSRF validation, and private identifiers.',
  }),
  Object.freeze({
    id: 'api:POST:/api/workspaces/[workspaceId]/invites',
    kind: 'api',
    method: 'POST',
    route: '/api/workspaces/[workspaceId]/invites',
    sourcePath: 'app/api/workspaces/[workspaceId]/invites/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-private-data',
    capture: false,
    rationale:
      'Invite creation consumes private identity data under authenticated workspace authority.',
  }),
  Object.freeze({
    id: 'api:PATCH:/api/workspaces/[workspaceId]/members/[memberId]/role',
    kind: 'api',
    method: 'PATCH',
    route: '/api/workspaces/[workspaceId]/members/[memberId]/role',
    sourcePath:
      'app/api/workspaces/[workspaceId]/members/[memberId]/role/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-private-data',
    capture: false,
    rationale:
      'Role mutation requires authenticated authority, CSRF validation, and private identifiers.',
  }),
  Object.freeze({
    id: 'api:DELETE:/api/workspaces/[workspaceId]/members/[memberId]',
    kind: 'api',
    method: 'DELETE',
    route: '/api/workspaces/[workspaceId]/members/[memberId]',
    sourcePath:
      'app/api/workspaces/[workspaceId]/members/[memberId]/route.ts',
    access: 'authenticated-parameterized',
    disposition: 'exclude-private-data',
    capture: false,
    rationale:
      'Member removal requires authenticated authority, CSRF validation, and private identifiers.',
  }),
]);

export const PUBLIC_API_METHOD_SURFACES = Object.freeze([
  ...PUBLIC_GET_API_SURFACES,
  ...NON_GET_API_METHOD_SURFACES,
]);

export const PUBLIC_SURFACES = Object.freeze([
  ...PUBLIC_PAGE_SURFACES,
  ...PUBLIC_METADATA_SURFACES,
  ...PUBLIC_STATIC_TEXT_SURFACES,
  ...PUBLIC_GET_API_SURFACES,
  ...NON_GET_API_METHOD_SURFACES,
]);

export const PUBLIC_CAPTURE_SURFACES = Object.freeze(
  PUBLIC_SURFACES.filter(
    (surface) =>
      surface.capture &&
      (!('method' in surface) || surface.method === 'GET')
  )
);
